// Run: node scripts/canvas-check.mjs [path-to-playwright] [preview-url]
import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { pathToFileURL } from 'node:url'
const { chromium } = await import(process.argv[2] ? pathToFileURL(join(process.argv[2], 'index.mjs')).href : 'playwright')
const output = join(tmpdir(), 'lifenode-ui-check')
const url = process.argv[3] || 'http://localhost:3000'
const fixture = (count) => ({
  nodes: [{ id: 'start', kind: 'start', x: 0, y: 0 }, ...Array.from({ length: count }, (_, i) => ({ id: `a${i}`, kind: 'aksi', lane: 'karir', label: `Decision ${i + 1}`, durasi: 1, intensity: 1, x: (i + 1) * 300, y: 0 })), { id: 'end', kind: 'end', x: (count + 1) * 300, y: 0 }],
  edges: Array.from({ length: count + 1 }, (_, i) => ({ id: `e${i}`, from: i === 0 ? 'start' : `a${i - 1}`, to: i === count ? 'end' : `a${i}` })),
  kondisiAwal: { umur: 20, uang: 100000, latarBelakang: '' },
})
const browser = await chromium.launch({ channel: 'msedge', headless: true })
await mkdir(output, { recursive: true })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const errors = []
  page.on('pageerror', (e) => errors.push(e.message))
  await page.goto(url, { waitUntil: 'networkidle' })
  async function load(count) {
    await page.evaluate((graph) => {
      localStorage.clear()
      localStorage.setItem('lifenode-graph', JSON.stringify({ state: graph, version: 0 }))
    }, fixture(count))
    await page.reload({ waitUntil: 'networkidle' })
    await page.locator('.react-flow__node-aksi').first().waitFor()
  }
  await load(2)
  assert.match(await page.locator('.resource-ledger').innerText(), /\$100,000/)
  await page.getByRole('button', { name: 'ID', exact: true }).click()
  assert.match(await page.locator('.resource-ledger').innerText(), /Rp100\.000/)
  assert.equal(await page.locator('.funds-input input').inputValue(), '100000')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await page.getByRole('button', { name: 'Tidy up node positions', exact: true }).click()
  await page.waitForTimeout(450)
  const viewport = page.locator('.react-flow__viewport')
  const pane = await page.locator('.react-flow__pane').boundingBox()
  const beforePan = await viewport.getAttribute('style')
  await page.mouse.move(pane.x + 40, pane.y + 40)
  await page.mouse.down({ button: 'middle' })
  await page.mouse.move(pane.x + 90, pane.y + 70, { steps: 8 })
  await page.mouse.up({ button: 'middle' })
  assert.notEqual(await viewport.getAttribute('style'), beforePan, 'Middle drag must pan')
  await page.locator('.react-flow__controls-fitview').click()
  await page.waitForTimeout(400)
  const first = page.locator('.react-flow__node-aksi').first()
  const beforeDrag = await first.getAttribute('style')
  const box = await first.boundingBox()
  await page.mouse.move(box.x + 12, box.y + 12)
  await page.mouse.down()
  await page.mouse.move(box.x + 32, box.y + 22, { steps: 5 })
  await page.mouse.up()
  assert.notEqual(await first.getAttribute('style'), beforeDrag, 'Left drag must move node')
  const beforeSelection = await viewport.getAttribute('style')
  await page.mouse.move(pane.x + 8, pane.y + 8)
  await page.mouse.down()
  await page.mouse.move(pane.x + pane.width - 8, pane.y + pane.height - 70, { steps: 12 })
  const selection = page.locator('.react-flow__selection')
  assert(await selection.isVisible())
  assert.equal(await selection.evaluate((el) => getComputedStyle(el).backgroundColor), 'rgba(59, 130, 246, 0.15)')
  await page.screenshot({ path: join(output, 'canvas-selection.png') })
  await page.mouse.up()
  assert.equal(await viewport.getAttribute('style'), beforeSelection, 'Left marquee must not pan')
  assert.equal(await page.locator('.react-flow__node-aksi.selected').count(), 2)
  await page.keyboard.press('Delete')
  await page.waitForFunction(() => document.querySelectorAll('.react-flow__node').length === 2)
  assert.equal(await page.locator('.react-flow__edge').count(), 0)
  await page.keyboard.press('Control+z')
  await page.waitForFunction(() => document.querySelectorAll('.react-flow__node').length === 4)
  assert.equal(await page.locator('.react-flow__edge').count(), 3)
  await first.getByRole('textbox', { name: 'Decision name', exact: true }).focus()
  await page.keyboard.press('Delete')
  await page.keyboard.press('Backspace')
  assert.equal(await page.locator('.react-flow__node').count(), 4)
  await load(7)
  assert(await page.locator('.life-minimap').isVisible())
  await page.getByRole('button', { name: 'Tidy up node positions', exact: true }).click()
  await page.waitForTimeout(400)
  assert.equal(await page.locator('.react-flow__minimap-node').count(), 9)
  await page.screenshot({ path: join(output, 'canvas-map-desktop.png') })
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  await mobile.addInitScript((graph) => localStorage.setItem('lifenode-graph', JSON.stringify({ state: graph, version: 0 })), fixture(7))
  await mobile.goto(url, { waitUntil: 'networkidle' })
  await mobile.locator('.react-flow__node').first().waitFor()
  assert(!(await mobile.locator('.life-minimap').isVisible()))
  const mobilePane = await mobile.locator('.react-flow__pane').boundingBox()
  const mobileViewport = mobile.locator('.react-flow__viewport')
  const beforeTouch = await mobileViewport.getAttribute('style')
  const cdp = await mobile.context().newCDPSession(mobile)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: mobilePane.x + 40, y: mobilePane.y + 40 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: mobilePane.x + 100, y: mobilePane.y + 80 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  assert.notEqual(await mobileViewport.getAttribute('style'), beforeTouch, 'Touch drag must pan')
  await mobile.screenshot({ path: join(output, 'canvas-map-mobile.png') })
  assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
  assert.deepEqual(errors, [])
  console.log(`Canvas controls, currency and responsive checks passed. Screenshots: ${output}`)
} finally {
  await browser.close()
}
